name = "SpikeSorting"
uuid = "acc641c0-d14d-5ed3-8a01-2b4adfca2b15"
version = "0.2.1"

[deps]
#Standard Library
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"

[compat]
julia = "1"
Cairo = "0.6, 0.7, 0.8, 1.0"
DistributedArrays = "0.6"
Gtk = "0.17, 0.18, 1.0, 1.1"
Interpolations = "0.9, 0.10, 0.11, 0.12"
MultivariateStats = "0.6, 0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
